apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feng-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-block-gold
  volumeMode: Filesystem